### ISSUE TITLE
Top Sites and Highlights "Tooltip Hints" button messages are displayed on top of the Search suggestion dropdown and Context Menu

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1605]
[Affected versions]:
- Nightly 52.0a1, Build ID 	20161020030211
- Activity Stream 1.1.6-dev

[Affected Platforms]:
- Windows 10 x64
- Mac OS 10.11

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Observe the Search suggestion dropdown.

[Expected results]:
- The Search suggestion dropdown is displayed without any foreign elements.

[Actual results]:
- "What's this?" messages are displayed on top of the Search suggestion dropdown.

[Notes]:
- The issue is also reproducible if you click the Context Menu for the 1st Top Sites tile.
- Attached a screenshot of the issue.
![topsites and highlights tooltips are on top](https://cloud.githubusercontent.com/assets/18304511/19593536/b6b9c354-9789-11e6-800d-a6d6757d5d16.gif)

**Comment by sarracini** [comment]
Fixed with #1646

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest dev build (1.1.6-1477699214). But on the Pre-release build (1.1.6-1477609010) it is still reproducible.
