### ISSUE TITLE
Bug 1279511 - Search keyword is removed after navigating with the arrow keys through the search suggestion dropdown

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#838]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279511
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a New Tab so the Activity Stream New Tab page is displayed.
3. Enter a keyword in the Search text box.
4. Navigate through the search suggestion dropdown with "down arrow" key from keyboard.
5. Return to the Search text box using the "up arrow" key from keyboard.

[Expected result]:
- The keyword written in the Search text box is displayed

[Actual result]:
- When returning to the Search text box using the "up arrow" key from keyboard, the keyword written is removed.

[Notes]:
- A video describing the issue was attached https://goo.gl/07ZYY9.

**Comment by SoftVision-CosminMuntean** [comment]
While testing the latest Activity Stream add-on (v1.1.0-custom build) we observed that when navigating through the search suggestion dropdown with "down arrow" or "up arrow" from keyboard, and after that hovering with the mouse cursor on the suggestion keywords, two elements will be highlighted (one will be highlighted from keyboard and one from mouse cursor).
<hr>
![two elements highlighted](https://cloud.githubusercontent.com/assets/19226534/16231700/120f1674-37d0-11e6-88cd-b1959bba4108.png)

**Comment by sarracini** [comment]
Fixed with #890

**Comment by SoftVision-VladBacia** [comment]
The issue described above by @SoftVision-CosminMuntean is still reproducible. If an item from the search suggestion dropdown list is hovered with the mouse cursor, it will be highlighted. While the item is highlighted press the "down arrow" or "up arrow" from keyboard. In this case there will be 2 items highlighted.
In `about:newtab` page when "down arrow" or "up arrow" button are pressed, only the last selected item is highlighted.

**Comment by sarracini** [comment]
I'm going to file a separate issue for that one

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160629030209) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.

**Comment by SoftVision-CosminMuntean** [comment]
@sarracini for the issue with the two highlighted items from suggestion dropdown, we have filed a separate bug #894.
